### ISSUE TITLE
Question: Possible to set enabled pins on Startup?

### ISSUE THREAD

**Issue by paradoxpotato** [sarfata/pi-blaster#102]
Hi there, I am looking for a way to set the pins that are enabled on startup/after boot if they are NOT included in the default list (to be precise 19,13,5). I know how to enable those pins by the gpio params, but not during bootup.

**Comment by sarfata** [comment]
Yes you can edit `/etc/default/pi-blaster` to pass the option when the daemon is started at boot. Just add them in the line `DAEMON_OPTS=""`. 

For example `DAEMON_OPTS="--gpio 19,13,5"` - That should work!

**Comment by paradoxpotato** [comment]
do i need to create the file first? i can't find the mentioned file.

**Comment by sarfata** [comment]
How did you install pi-blaster so that it would start automatically?

**Comment by paradoxpotato** [comment]
i copied it via wget, cd'ed into the folder and started sudo make-install (after installing autoconf i think). Is there a better way? I am quite new in the linux world :)

**Comment by paradoxpotato** [comment]
it seems to work now, at least sudo service pi-blaster status says it is active now. thank you very much :)

**Comment by sarfata** [comment]
👍
