### ISSUE TITLE
The X server does not works with pi-blaster

### ISSUE THREAD

**Issue by GCorbel** [sarfata/pi-blaster#16]
Hello,

I have a raspberry-pi with the raspbian os. I tried to install pi-blaster. It works for a short time but after a while, the serve x is frozen and I must to reboot the raspberry. 

When I reboot and I try to do a `startx` it crash (I have a black screen).

When I do a `killall pi-blaster`, I works. When I try to reinstall pi-blaster, it does not works. I need to uninstall pi-blaster, remove the repository (just delete the repository made by `make` is not enough), reclone the project with github and reinstall it to make it working.

I tried to don't start the x server and it seems to work fine.

I don't have an error trace. What can I do to help you to solve the problem?

**Comment by phueper** [comment]
Could you try with the changes in PR #38? Since we are now using the gpu mbox command to allocate memory for the DMA control blocks,  maybe this is solved? It is just a wild guess though ;-)

**Comment by phueper** [comment]
Ok... now with https://github.com/phueper/pi-blaster/commit/3b93b215ce1087a9ec3c72408cc9190ff4bb54d9 it is more than a wild guess...  i think this should be fixed in PR #38

**Comment by sarfata** [comment]
Works now (thanks to #38 probably)
