### ISSUE TITLE
drag window in raspbian causes system to crash

### ISSUE THREAD

**Issue by amcc** [sarfata/pi-blaster#27]
after installing and running pi-blaster i'm getting a crash if i drag any window in the os. This only happens when pi-blaster is running and i'm using raspbian and trying to drag an os window (such as the file manager)

i've just wiped and re-installed raspbian from scratch to see if something else was causing this and i'm still getting the same thing.

This is a fresh install of noobs raspbian with only the following additions
- geany: ('sudo apt-get install geany')
- ssh turned on
- autoconf (as instructed in pi-blaster installation process)

that said - its all working really well and i'm having no trouble running the script from the command line and i'm ok so long as i dont move a window when the os is running

**Comment by Keridos** [comment]
Provide a strace please with this command:
```strace /usr/sbin/pi-blaster 2>&1 >/tmp/pi-blaster-logs.txt```

**Comment by phueper** [comment]
Could you try with the changes in PR #38? Since we are now using the gpu mbox command to allocate memory for the DMA control blocks,  maybe this is solved? It is just a wild guess though ;-)

**Comment by phueper** [comment]
Ok... now with https://github.com/phueper/pi-blaster/commit/3b93b215ce1087a9ec3c72408cc9190ff4bb54d9 it is more than a wild guess...  i think this should be fixed in PR #38

**Comment by sarfata** [comment]
fixed thanks to #38
