### ISSUE TITLE
Request: blink feature

### ISSUE THREAD

**Issue by ctshh** [sarfata/pi-blaster#36]
I'd like to ask for a `blink` feature.
I use `pi-blaster` quite successfully to update a few status-LEDs, yet for making them blink I need to wrench things in `bash` that, well, should not be touched by a scripting language (ie. fork thins in the bg, then kill them later - *yuck*).

If `pi-blaster` would accept a `blink` tag and an on/off ratio in milliseconds any type of blinkenlights should be created quite easily.

**Comment by sarfata** [comment]
Do you mean blinking forever? Or turn on and then off?

If you want to blink forever, you can already do it. You just need to increase the CYCLE_TIME in the source.

For example, with this change you will have a maximum period of 3 seconds:
````
pi@openplotter:~/pi-blaster $ git diff
diff --git a/pi-blaster.c b/pi-blaster.c
index c7a0152..552244a 100644
--- a/pi-blaster.c
+++ b/pi-blaster.c
@@ -84,8 +84,8 @@ static uint8_t pin2gpio[16];
 // will use too much memory bandwidth.  10us is a good value, though you
 // might be ok setting it as low as 2us.
 
-#define CYCLE_TIME_US  10000
-#define SAMPLE_US              10
+#define CYCLE_TIME_US  3000000
+#define SAMPLE_US              1000
 #define NUM_SAMPLES            (CYCLE_TIME_US/SAMPLE_US)
 #define NUM_CBS                        (NUM_SAMPLES*2)
````

If you want to turn on and off later (but not periodic), then this is similar to #6 so I will close this issue anyway.
