### ISSUE TITLE
Is it possible to read the current value using piblaster?

### ISSUE THREAD

**Issue by TylerWilcock** [sarfata/pi-blaster#37]
I'm attempting to build a movable camera that is hooked up to a web interface (and obviously a servo).  I'm using piblaster to control the servo, and I want the user to be able to click a "left" button on the webpage, and use PHP to execute pi blaster via the command line.  Everything is all set up - there's only one problem.  In order to move the servo to the left, I need to increment/decrement the current PWM output of the specified pin.  Unless there is a built in way to do this, I would need to first read the pin's current PWM value, increment it, and then execute echo "17=<newValue>" > /dev/pi-blaster.

Is it possible to read the current value of pins used by pi blaster?  If not, is there some way I can accomplish this task with pi blaster's tools?

**Comment by sarfata** [comment]
There are many ways to do this but piblaster currently is not one of them. Maybe the easiest would be to use a temporary file to save the last value written.
