### ISSUE TITLE
Pi-blaster is not properly working on full rotation motor as ServoBlaster works

### ISSUE THREAD

**Issue by S0nam** [sarfata/pi-blaster#44]
I am using Pi-2 and Servoblaster crashes it every time than I installed Pi-blaster on Pi-2.But when I am giving the rotation command to pi-blaster , it rotates contentiously.I only wants to rotate it as Servo-blaster.

**Comment by sarfata** [comment]
pi-blaster is not the same thing as servoblaster. It sends PWM command, not angle of rotations for servo which require a different type of pulses.
