### ISSUE TITLE
lowest value

### ISSUE THREAD

**Issue by nhooyr** [sarfata/pi-blaster#70]
What is the lowest value I can set a gpio pin to?

**Comment by penfold42** [comment]
0 ?

**Comment by nhooyr** [comment]
oh I meant lowest above 0

**Comment by nhooyr** [comment]
nevermind, I think I got it, its 1 divided by the number of steps.

**Comment by penfold42** [comment]
And the readme recommends 2uS as the smallest step value

**Comment by sarfata** [comment]
:+1:
