### ISSUE TITLE
systemd problems

### ISSUE THREAD

**Issue by nhooyr** [sarfata/pi-blaster#71]
First, why is `/etc/default/pi-blaster` not created automatically before enabling/starting the service in the makefile? A simple `touch /etc/default/pi-blaster` is all that is required. Or maybe this should be done by the package manager. The AUR package does not handle it though.

Second, on arch linux, you cannot run makepkg as root and so when `systemd enable pi-blaster.service` is run [here](https://github.com/sarfata/pi-blaster/blob/d2869cee24903998a6e8baf3387b6238064e874b/Makefile.am#L17), it fails. Perhaps change this to `sudo systemd enable pi-blaster.service`? 
IMO systemd should not be handled like this in the makefile. Allow the user to start/enable it on their own.

Third, I also noticed that for some reason, these log messages:

```
Jun 11 11:03:15 nepu pi-blaster[1274]: MBox Board Revision: 0xa21041
Jun 11 11:03:15 nepu pi-blaster[1274]: DMA Channels Info: 0x7f35, using DMA Channel: 14
Jun 11 11:03:15 nepu pi-blaster[1274]: Using hardware:                   PWM
Jun 11 11:03:15 nepu pi-blaster[1274]: Number of channels:                32
Jun 11 11:03:15 nepu pi-blaster[1274]: PWM frequency:                 100 Hz
Jun 11 11:03:15 nepu pi-blaster[1274]: PWM steps:                       1000
Jun 11 11:03:15 nepu pi-blaster[1274]: Maximum period (100  %):      10000us
Jun 11 11:03:15 nepu pi-blaster[1274]: Minimum period (0.100%):         10us
Jun 11 11:03:15 nepu pi-blaster[1274]: DMA Base:                  0x3f007000
Jun 11 11:03:15 nepu pi-blaster[1274]: Initialised, Daemonized, Reading /dev/pi-blaster.
Jun 11 11:03:15 nepu pi-blaster[1274]: pi-blaster stopped.
```

Only appear when `pi-blaster.service` is stopped, not when it is started. Weird. Works fine if I start it in the terminal.

Lastly, stopping `pi-blaster.service` should not cause the unit to fail, but it does. The process should not exit with a status one code when stopped.

**Comment by sarfata** [comment]
Thanks for the comments. I am not an Arch user so I cannot test this. Can you make a pull-request?

**Comment by doudz** [comment]
sudo touch /etc/default/pi-blaster did the trick on my fresh installed jessie on rpi 2

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
