### ISSUE TITLE
Cannot use pin after releasing it

### ISSUE THREAD

**Issue by ChrisTrenkamp** [sarfata/pi-blaster#74]
I'm running a minimal Gentoo installation with Busybox on a RPI B+.  When starting the daemon for the first time, everything's fine.  After releasing a pin and try turning it on again, it doesn't work.  The pwm frequency operates very funkily, and after releasing the pin again, it doesn't work at all.

I thought this was a feature at first, but after using this fork: [https://github.com/hybridgroup/pi-blaster](https://github.com/hybridgroup/pi-blaster), I don't see the same behaviour.  The pin starts and stops with no problem.

**Comment by sasanrose** [comment]
Same problem here. I am using minibian on RPI B+

**Comment by sasanrose** [comment]
I tried to do a git bisect and seems that the problem was introduced in e0cb6de39798e6ac2f6dfacffc4b468dffda4ffb

I think when you run `pi-blaster -D` (Which means no daemonize) then everything works finde

**Comment by ollyhayes** [comment]
Yeah this is happening to me too, not every time I release, but most times. Sometimes it just one pin (but always the same one), but most of the time it's both. I have to stop and start the daemon to get it work again.

For me running pi-blaster -D without the daemon running made no difference. Did you ever get to the bottom of it?

I'm on a raspberry pi 3, running raspbian, and I'm driving two externally powered servo motors.

**Comment by DaBlitzStein** [comment]
Here Pi 3 with raspbian and the same with or without -D . When my gobot program stops, I have to restart pi-blaster service to use these pins.

**Comment by mikegleasonjr** [comment]
Same here...

**Comment by dankozlowski** [comment]
The issue with setting it to `0` is that the line is still open, and you can get minor jitter.

**Comment by bezineb5** [comment]
This issue should be resolved now, with the PR #101

**Comment by sarfata** [comment]
Thank you @bezineb5 !
