### ISSUE TITLE
tutorials/examples?

### ISSUE THREAD

**Issue by Ch3fk0ch88** [sarfata/pi-blaster#86]
Hi,
are there some tutorial/example script for Pi-Blaster.(dim an LED slowly over 30min or something like that?).

And how the installation works?
Everywere i read are 4 steps:

> sudo apt-get install autoconf
> ./autogen.sh
> ./configure
> make
> sudo make install

first step works and than ?? when i enter ./autogen.sh he sait there is nothing with that name.

**Comment by penfold42** [comment]
Did you download the source code and cd into the pi-blaster directory ?

**Comment by Ch3fk0ch88** [comment]
Ye, after a bit of search i found the way to install it.

But are the python or java exampels`?

**Comment by Ch3fk0ch88** [comment]
Did no one have an idear where i can find an example?
I find nothing with pi-blaster.

**Comment by git0rhero** [comment]
What you need is an example of how to write to a file path in those languages. Then you just need to write to /dev/pi-blaster . Same as you would with the shell command 'echo' in the example in the readme.

**Comment by Ch3fk0ch88** [comment]
Ok i will search for it (I wanted to use python)

**Comment by Ch3fk0ch88** [comment]
Ok, to write something in a fifo file i need the name of it xxxx.fifo.
But what is the name?
Or create "echo "17=1" > /dev/pi-blaster" a file?

I dont check it.

**Comment by git0rhero** [comment]
The name is /dev/pi-blaster. It is created when you run 'sudo ./pi-blaster'
Is it that what you mean or am I on a wood way? ;)

**Comment by Ch3fk0ch88** [comment]
But i can't open a file "/dev/pi-blaster" cause it is no file.
A File would be pi-blaster.fifo

**Comment by Ch3fk0ch88** [comment]
No one?

**Comment by RunnicFusion** [comment]
What todo after installing autoconf? What is the next step to get pi blaster installed? Git cloned the repo into dev/pi-blaster

**Comment by gherlein** [comment]
@RunnicFusion this is probably not the forum to ask basic howto compile questions... did you follow the instructions at https://github.com/sarfata/pi-blaster#build-and-install-directly-from-source ???

**Comment by gherlein** [comment]
@Ch3fk0ch88  are you sure you have installed it correctly?  do a 'sudo ps aux|grep blaster' and you should see it running.  If it's running, can you do the steps at https://github.com/sarfata/pi-blaster#how-to-use ???  There are detailed instructions.  If you follow them and post your outputs and ask clear questions we can likely help you.  You really have not provided much about what you see or don't see.  Consider reading:  http://www.catb.org/esr/faqs/smart-questions.html

**Comment by sarfata** [comment]
@gherlein great ESR link, thanks for sharing!
