### ISSUE TITLE
Extend the number of gpio pins?

### ISSUE THREAD

**Issue by s1nn3r** [sarfata/pi-blaster#9]
Hi,
I am very interested in this project as I am planning to have my PI control several RGB-LED strips using PWM.
In fact I need to control 7 different RGB-LED strips, that means I would need 21 gpio pins for that (+ one analogue input + one digital input).
Is there a way to establish that with the PI? Any ideas?

Is the PWM-controlling fast enough to "fade" the colors? Means send about 5 color-changes (to 3 pins) per second?

Thanks in advance,
Marc

**Comment by improti** [comment]
This is so old, it makes me rofl. Why aren't these closed? But on the (off-topic) topic and just in case someone stumbles upon this ... If you need more ports for that specific purpose, you might as well consider breakouts like the [I2C 16-channel PWM/Servo from Adafruit](https://www.adafruit.com/products/815) instead. You wouldn't need pi-blaster then but control the PWM via I2C instead.

**Comment by sarfata** [comment]
good point. closing.
